import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DataContextProvider } from "@/contexts/dataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Material Flow Manager",
  description: "Generated by create next app",
  icons: {
    icon: "/logotr.png", // tu nuevo ícono
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <DataContextProvider>{children}</DataContextProvider>
      </body>
    </html>
  );
}
